name: S3 Publish Files Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: S3 Publish Docker Action
        uses: saurabhbothra/s3-publish-docker-action@v2
        with:
          args: --delete --exclude '.github/*'
        env:
          S3_BUCKET_NAME: 'my-aef-bucket'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: 'us-west-2'
          SOURCE_DIR: './'
          TARGET_DIR: 'folderA/'

